### ISSUE TITLE
Detect invalid bytes

### ISSUE THREAD

**Issue by moteus** [kikito/utf8_validator.lua#1]
I use your library to validate stream of bytes. 
So at some stage I have only part of string (not full message) and I store `tail` starting from first error 
byte. (https://github.com/moteus/lua-lluv-websocket/blob/master/src/lluv/websocket/utf8.lua#L38-L47)
But I can not tell if this is invalid byte and I should stop validate stream or it just incomplite string and I need wait more data.
Is it possible add functionality that validate function does not return `pos` if string contain invalid byte.

**Comment by kikito** [comment]
Hi there!

I think I understand everything you said except the last line:

> Is it possible add functionality that validate function does not return pos if string contain invalid byte.

Are you talking about my library, or yours on that line? If you are talking about mine, please try explaining it with different words. Maybe add some code exemplifying what you are trying to accomplish - I am not able to understand what you need.

**Comment by moteus** [comment]
``` Lua
function H(str)
  local s = ''
  string.gsub(str, "(%x%x)", function(c) s .. string.char(tonumber(c, 16))  end)
  return s
end

-- Test case from AutoBahnTestSuit (testcase 6.4.2)
ok, pos = utf8_validator(H"cebae1bdb9cf83cebcceb5f4") 
-- returns `true, 12` because we get incomplete codepoing

ok, pos = utf8_validator(H"cebae1bdb9cf83cebcceb5f4" .. H"90")
-- But when we get next byte(0x90) we get invalid codepoint (0xf4 0x90 - out of range)
-- here I wont get `nil, nil` to indicate that I do not need wait more data to tell that this 
-- stream is invalid UTF8
```

**Comment by kikito** [comment]
All `utf8_validator` is doing is checking whether string is valid or not.

I have tried your code. I think you are missing a `return` in the internal function of H:

``` lua
function H(str)
  local s = ''
  string.gsub(str, "(%x%x)", function(c) return s .. string.char(tonumber(c, 16))  end)
  return s
end
```

Also, this code:

``` lua
ok, pos = utf8_validator(H"cebae1bdb9cf83cebcceb5f4") 
```

returns just `true`, not `true, 12`. It returns true because the string is valid utf8 - no missing codepoints. I think.

``` lua
ok, pos = utf8_validator(H"cebae1bdb9cf83cebcceb5f4" .. H"90")
```

That also returns true. No errors.

**Comment by moteus** [comment]
> All utf8_validator is doing is checking whether string is valid or not.

I know that :). But this addition make library more convinient to stream validation.
It is not neccessary to me. I can just test `tail` length  and if if greater than 4  then this is invalid stream.

> I have tried your code. I think you are missing a return in the internal function of H:

No I use accumulator `s`  to support `H"AA AB-DC"`

I just run this code

``` Lua
local validator = require "utf8_validator"

print(validator(H"cebae1bdb9cf83cebcceb5f4"))            -- false, 12
print(validator(H"cebae1bdb9cf83cebcceb5f4" .. H"90" ))  -- false, 12
print(validator(H"cebae1bdb9cf83cebcceb5f4" .. H"90" .. H"8080656469746564")) -- false, 12
```

**Comment by kikito** [comment]
All those lines return true for me -  I just tried.

Are you sure you are using the same utf8_validator that I have?

**Comment by moteus** [comment]
Sorry wrong `H` function

``` Lua
function H(str)
  local s = ''
  string.gsub(str, "(%x%x)", function(c) s = s .. string.char(tonumber(c, 16))  end)
  return s
end
```

**Comment by kikito** [comment]
Hi,

I confirm that they all return false, 12 with the new H function.

> I know that :). But this addition make library more convinient to stream validation.

If a string is passed to the validator, I think it is desirable (and expected) that the string is validated as a single piece. In that sense, I think returning false in your previous example is the right thing to do (because you pass it a string, not a stream).

Lua has no streams as far as I know - we could try and see. It has functions and coroutines though. Do you have any thoughts on this direction? Would some kind of "callback-based" mechanism be acceptable?

**Comment by kikito** [comment]
Closing this down as it is old
